### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by halkeye** [armentalis/matrix-synapse-keycloak#1]
Does this still work?

```
  File "/usr/local/lib/python3.7/site-packages/synapse/handlers/auth.py", line 86, in <listcomp>
    for module, config in hs.config.password_providers
  File "/data/password_providers/keycloak_auth_provider.py", line 39, in __init__
    self.store = self.account_handler.hs.get_datastore()
AttributeError: 'ModuleApi' object has no attribute 'hs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.7/site-packages/synapse/app/homeserver.py", line 404, in start
    _base.start(hs, config.listeners)
  File "/usr/local/lib/python3.7/site-packages/synapse/app/_base.py", line 287, in start
    sys.exit(1)
SystemExit: 1

```

https://github.com/armentalis/matrix-synapse-keycloak/blob/master/keycloak_auth_provider.py#L39

**Comment by halkeye** [comment]
Looks like hs is now private
https://github.com/matrix-org/synapse/blob/6b0ef34706e32121ff6f802d62b3eb8545785afe/synapse/module_api/__init__.py#L40

I think https://github.com/armentalis/matrix-synapse-keycloak/blob/master/keycloak_auth_provider.py#L144 should be 
        `self.store.runInteraction("save_keycloak_token", _save_keycloak_token)` should be `self.account_handler.run_db_interaction`

**Comment by shkuropat** [comment]
Thanks, for your investigation.
We not upgraded yet, but in any case I will check it after weekend.
